### PR TITLE
[TT-7642] Reduce CVE surface by removing cURL

### PR DESCRIPTION
**Pull request by buger**
Reduce Ensure that curl is removed when it no longer needed. At the moment it accounts for a few critical/high vurneabilities flagged by dockerhub.

### CODE REVIEW

**Comment by buger** [comment]
I assume CI failures from Dr.Releng not related to my PR.

**Comment by alephnull** [comment]
Thank you for your help in maintaining the templates :muscle:  
Yes, Dr. Releng :pill:  is new to his job.
This should be merged only after https://github.com/TykTechnologies/tyk/pull/4662 is work as expected.

**Comment by buger** [comment]
Apart from failing smoke test, dockerhub shows that CVE issue was fixed https://hub.docker.com/layers/tykio/tyk-gateway/v5.0rc1/images/sha256-bf807a76a6b97934cbdcc01b888b8686a0334bbdcb0cf03639b8f3dd73371a14?tab=vulnerabilities

**Review by titpetric — APPROVED** [review]

**Review by jeffy-mathew — APPROVED** [review]

**Comment by jeffy-mathew** [comment]
The smoke tests are failing with naming inconsistencies of plugin name output by the plugin compiler and name used in docker compose. verified locally

**Comment by buger** [comment]
@alephnull feel free to merge it, and update master, release-4 and release-4.3 branches with a fix. Thanks all!

**Pull request merged**
