### PR TITLE
Override isn't a valid input for upload-artifact@v4

### PR DESCRIPTION
**Pull request by asutosh**
`Override` doesn't seem to be a valid option for upload-artifact@v4.
See the warning on the run below:
https://github.com/TykTechnologies/tyk/actions/runs/8262826493/job/22603310931?pr=6138#step:11:1

### CODE REVIEW

**Comment by alephnull** [comment]
@ermirizio Does this need to be foxed further?

**Comment by ermirizio** [comment]
@alephnull the correct attribute is 'overwrite' not 'override' my bad. I will send a fix on this PR

**Comment by ermirizio** [comment]
no more warning with this change @asutosh 
image
feel free to merge as it is now

**Review by ermirizio — APPROVED** [review]
👍

**Pull request merged**
