### PR TITLE
[TD-918]: Implementing releng bundle using gromit policy with multiple version support.

### PR DESCRIPTION
**Pull request by asutosh**
This PR will
- Translate the m4 templates to go templates for direct rendering of releng code with gromit policy.
-  ~~Will add support for multiple versions(from within the templates)~~ => To be done in a subsequent PR.

### CODE REVIEW

**Comment by alephnull** [comment]
This approach is fine. We'll have to fix the tests though. I'll work on applying auth from TD-1025 in this PR.

**Comment by asutosh** [comment]
All the files managed by `tyk-ci` except the `goreleaser-el7.yml` has been converted to text/template, and is generated for gateway.
Generated test PR is here: https://github.com/tyklabs/tyk/pull/8.

**Comment by alephnull** [comment]
> test PR is here: [tyklabs/tyk#8](https://github.com/tyklabs/tyk/pull/8)
Please create a PR on TykTechnologies/tyk for testing.

**Comment by asutosh** [comment]
> Please create a PR on TykTechnologies/tyk for testing.

Created one here: https://github.com/TykTechnologies/tyk/pull/4148

**Comment by asutosh** [comment]
https://github.com/TykTechnologies/tyk/pull/4157

Release successful in this PR, after the fix above.

**Comment by alephnull** [comment]
Please update this PR to update Dockerfile.std as suggested by @titpetric in https://github.com/TykTechnologies/tyk/pull/4157
This PR can be merged after https://github.com/TykTechnologies/tyk/pull/4157 is merged.

**Comment by asutosh** [comment]
@alephnull I've also added the el7 changes in this PR itself, since it's only a few files, will additionally add the latest dockerfile changes too.

**Comment by alephnull** [comment]
Sounds good @asutosh. The plan is,
- make https://github.com/TykTechnologies/tyk/pull/4157 merge-able to master
- merge https://github.com/TykTechnologies/tyk/pull/4157
- wait 3-4 days for real world testing
- make any needed changes to this PR
- merge this PR

**Review by alephnull — APPROVED** [review]
Please merge when convenient.

**Comment by alephnull** [comment]
@asutosh Lets setup a pairing session to fix these tests. Since we are going to use gromit in the short-term, these tests need to be fixed.

**Pull request merged**
