### PR TITLE
Tyk-analytics Go bump to 1.19

### PR DESCRIPTION
**Pull request by titpetric**
Update master branches with overrides for required tests and goversion (tyk-analytics)

### CODE REVIEW

**Comment by ermirizio** [comment]
@titpetric should this go for gw and analytics UI as well?

**Comment by ermirizio** [comment]
@titpetric should this go for gw and analytics UI as well?

**Comment by titpetric** [comment]
> @titpetric should this go for gw and analytics UI as well? Changes have been added to this PR along with other relates changes [TykTechnologies/tyk-analytics#3011](https://github.com/TykTechnologies/tyk-analytics/pull/3011)

Step by step, tyk-analytics first. One area at a time.

**Comment by alephnull** [comment]
Please make these changes in the repo directly. The templates can be updated when you have everything working as needed.

**Comment by alephnull** [comment]
Obsolete.

**Pull request closed without merging**
